# The purpose of this action is to build the contents of this repository into an SBOL package
name: packaging

# Controls when the action will run.
on:
  [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository for building
        uses: actions/checkout@v3

      - name: Make sbol file from xlsx
        uses: actions/make-sbol@v1